spring:
  application:
    name: einvoice-demo
  datasource:
    url: jdbc:mysql://localhost:3306/einvoice
    username: root
    password: manager
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  thymeleaf:
#    prefix: file:src/main/java/com/pvs/
#    suffix: .html
server:
  port: 9999
logging:
  level:
     org.springframework.security : debug



